#!/usr/bin/env python3
"""Add server-generated DOCX artifacts to a browser export audit record.

The browser audit owns JSON/CSV/print-PDF files.  DOCX is generated by the
backend report endpoint, so this small, deterministic post-step records both
artifacts under the same run identity without re-running the model.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from docx import Document


def _file_meta(path: Path) -> dict[str, object]:
    return {
        "path": str(path),
        "bytes": path.stat().st_size,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "exists": path.is_file(),
    }


def _docx_text(path: Path) -> str:
    document = Document(path)
    text = "\n".join(paragraph.text for paragraph in document.paragraphs)
    text += "\n" + "\n".join(
        cell.text
        for table in document.tables
        for row in table.rows
        for cell in row.cells
    )
    return text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--audit", type=Path, required=True)
    parser.add_argument("--main-docx", type=Path, required=True)
    parser.add_argument("--live-docx", type=Path, required=True)
    args = parser.parse_args()

    audit_path = args.audit.resolve()
    report = json.loads(audit_path.read_text(encoding="utf-8"))
    exports = report.setdefault("exports", {})
    for key, path in (("main", args.main_docx), ("live", args.live_docx)):
        path = path.resolve()
        exports.setdefault(key, {})["docx"] = _file_meta(path)
        exports[key]["docx_is_openxml"] = path.is_file() and path.read_bytes()[:2] == b"PK"
        identity = exports[key].get("run_id")
        if key == "live" and not identity:
            live_json = audit_path.parent / "live-sample.json"
            if live_json.is_file():
                live_payload = json.loads(live_json.read_text(encoding="utf-8"))
                identity = (
                    live_payload.get("task", {})
                    .get("result", {})
                    .get("analysis", {})
                    .get("run_id")
                )
                if identity:
                    exports[key]["run_id"] = identity
        text = _docx_text(path) if path.is_file() else ""
        exports[key]["docx_contains_identity"] = bool(identity and str(identity) in text)
        exports[key]["docx_has_ai_notice"] = "AI生成内容" in text

    report["structured_export_formats"] = ["json", "csv", "print_pdf", "docx"]
    report["docx_backend_endpoint"] = "/api/runs/{run_id}/report.docx"
    report["docx_same_run_identity"] = bool(
        exports.get("main", {}).get("run_id")
        and exports.get("live", {}).get("task_id")
        and exports.get("main", {}).get("docx", {}).get("exists")
        and exports.get("live", {}).get("docx", {}).get("exists")
        and exports.get("main", {}).get("docx_contains_identity")
        and exports.get("live", {}).get("docx_contains_identity")
        and exports.get("main", {}).get("docx_has_ai_notice")
        and exports.get("live", {}).get("docx_has_ai_notice")
    )
    audit_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"audit": str(audit_path), "docx_same_run_identity": report["docx_same_run_identity"]}, ensure_ascii=False))
    return 0 if report["docx_same_run_identity"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
